abstract class ProfessionalEmploymentState {}

class MainInitial extends ProfessionalEmploymentState {}

class GetProfessionalEmploymentLoadingState extends ProfessionalEmploymentState {}

class GetProfessionalEmploymentSuccessState extends ProfessionalEmploymentState {}

class GetProfessionalEmploymentErrorState extends ProfessionalEmploymentState {}

class ChangeStatusOfSelectedIndexOrder extends ProfessionalEmploymentState {}
class GetProfessionalEmploymentLoadingMoreState extends ProfessionalEmploymentState {}
class ArchiveProfessionalEmploymentSuccessState extends ProfessionalEmploymentState {}
class ArchiveProfessionalEmploymentErrorState extends ProfessionalEmploymentState {}

class ArchiveProfessionalEmploymentLoadingState extends ProfessionalEmploymentState {}
